apiVersion: v2
appVersion: 3.137.0
dependencies:
- condition: postgresql.deploy
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.4.9
- condition: clickhouse.deploy
  name: clickhouse
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 8.0.5
- alias: redis
  condition: redis.deploy
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.2.4
- alias: s3
  condition: s3.deploy
  name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.10.5
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.30.0
description: Open source LLM engineering platform - LLM observability, metrics, evaluations,
  prompt management.
home: https://langfuse.com/
icon: https://langfuse.com/langfuse_logo.png
keywords:
- langfuse
- llm
- observability
- prompt management
- metrics
maintainers:
- email: contact@langfuse.com
  name: langfuse
  url: https://langfuse.com/
name: langfuse
sources:
- https://github.com/langfuse/langfuse
- https://github.com/langfuse/langfuse-k8s
type: application
version: 1.5.14
